name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # Use the appropriate .NET version for your project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip published files
        run: zip -r deploy-package.zip ./publish

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Specify your AWS region
        run: |
          aws elasticbeanstalk create-application-version --application-name your-app-name --version-label ${{ github.sha }} --source-bundle S3Bucket="your-s3-bucket-name",S3Key="deploy-package.zip"
          aws elasticbeanstalk update-environment --environment-name your-env-name --version-label ${{ github.sha }}
